### ISSUE TITLE
sprint todo

### ISSUE THREAD

**Issue by cekees** [erdc/hrw_duck_15#1]
## Chris
- [x] Write initial wave function module
- [ ] context implementation, refactorization example of v-v subdir
## Aggelos
- [x] Add OpenFOAM Hex Mesh
- [ ] Walk through BC module with Aron and Chris, and iterate on development
- [ ] Write a test.py in each Goal: `nosetests -vv daily/weekly/monthly` or something 
## Aron
- [x] Set up initial static website framework with Sphinx (possibly mimic proteus)
- [ ] Example problem landing page
  - High-res 3D pretty video (MARIN)
  - Interactive notebook (Ubbink 2D)
- [x] Set up or decide  on place to put large binaries (images, animations, data sets)
- [ ] Set up initial web server somewhere (github is fine)
- [ ] protype notebooks to link to and spawn on tmpnb
## Matthew
- [ ] Write initial OpenFOAM reader
